uploads = []

[[generated]]
id = "JPFdv_fVLzyBhLVyKtKLh"
uri = "file://client/src/assets/hero-bg.png"
type = "image"
title = "abstract futuristic dark grid background"

[[generated]]
id = "VrKDF39re-IDVhHsV1er3"
uri = "file://client/src/assets/avatar.png"
type = "image"
title = "professional developer avatar"

[[outputs]]
id = "zmTVjLpJ7NR4gEkCFhSsw"
uri = "file://client/src/assets/exclusive-kitchen.jpg"
type = "image"
title = "delicious african food meal restaurant jollof rice plantain"

[[outputs]]
id = "l741cX_d8R5Eb9V9ApNUT"
uri = "file://client/src/assets/invoice-link.jpg"
type = "image"
title = "Invoice receipt checkout mobile payment"

[[outputs]]
id = "4darZgdSg-c_ViNokMg8K"
uri = "file://client/src/assets/lumina-ai.jpg"
type = "image"
title = "Artificial intelligence digital technology nodes"

[[outputs]]
id = "MaP1rABY2bcUmQQtfgya9"
uri = "file://client/src/assets/invoice-real.jpg"
type = "image"
title = "invoice receipt paper document"

[[outputs]]
id = "M2Odnmvziv1052algEXuK"
uri = "file://client/src/assets/lumina-ai-art.jpg"
type = "image"
title = "artificial intelligence neural network glowing digital lines technology concept"
